### ISSUE TITLE
Can we make the input fields and color pickers bigger

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-buttons#14]
At the moment they are very small - can we make the the same nice height as in shortcodes ulitmate - it's also really nice the way the input field changes color. 

![screen shot 2016-02-25 at 19 24 25](https://cloud.githubusercontent.com/assets/3070779/13331445/6974d21e-dbf5-11e5-80e4-9a21e3b01c63.png)

**Comment by shramee** [comment]
Made 'em wp color pickers ;)
